-- ============================================================================
-- SCal Mobile RMA Dashboard - Snowflake Database Schema
-- Production-Grade Architecture for Returns Management
-- ============================================================================

-- ============================================================================
-- 1. DATABASE & SCHEMA SETUP
-- ============================================================================

CREATE DATABASE IF NOT EXISTS SCAL_RMA_DB;

-- Create schemas for data pipeline stages
CREATE SCHEMA IF NOT EXISTS SCAL_RMA_DB.LANDING;      -- Raw ingestion
CREATE SCHEMA IF NOT EXISTS SCAL_RMA_DB.STAGING;      -- Cleaned data
CREATE SCHEMA IF NOT EXISTS SCAL_RMA_DB.PRODUCTION;   -- Analytics-ready
CREATE SCHEMA IF NOT EXISTS SCAL_RMA_DB.ARCHIVE;      -- Historical data
CREATE SCHEMA IF NOT EXISTS SCAL_RMA_DB.SYSTEM;       -- System tables

-- ============================================================================
-- 2. LANDING ZONE - Raw Data Capture (Immutable)
-- ============================================================================

CREATE OR REPLACE TABLE SCAL_RMA_DB.LANDING.RMA_SUBMISSIONS_RAW (
    -- System Fields
    SUBMISSION_ID VARCHAR(50) PRIMARY KEY,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'WEB_PORTAL',
    RAW_PAYLOAD VARIANT,

    -- Customer Information
    COMPANY_NAME VARCHAR(255),
    COMPANY_EMAIL VARCHAR(255),
    ORDER_NUMBER VARCHAR(100),
    CUSTOMER_TYPE VARCHAR(20),

    -- Submission Metadata
    SUBMISSION_DATE DATE,
    INVOICE_NUMBER VARCHAR(100),
    RETURN_QUANTITY INTEGER,
    REPAIR_QUANTITY INTEGER,
    TOTAL_RETURN_VALUE DECIMAL(10,2),
    TOTAL_REPAIR_VALUE DECIMAL(10,2),

    -- File Tracking
    UPLOADED_FILES ARRAY,
    FILE_COUNT INTEGER,

    -- Processing Status
    PROCESSING_STATUS VARCHAR(20) DEFAULT 'PENDING',
    ERROR_MESSAGE VARCHAR(5000),
    PROCESSED_TIMESTAMP TIMESTAMP_NTZ
);

-- ============================================================================
-- 3. STAGING ZONE - Normalized Device Data
-- ============================================================================

CREATE OR REPLACE TABLE SCAL_RMA_DB.STAGING.RMA_DEVICE_ITEMS (
    DEVICE_ITEM_ID VARCHAR(100) PRIMARY KEY,
    SUBMISSION_ID VARCHAR(50),
    
    -- Device Fields (from customer Excel files)
    IMEI VARCHAR(15) NOT NULL,
    MODEL VARCHAR(100),
    STORAGE VARCHAR(20),
    STATUS VARCHAR(50),
    INV VARCHAR(50),
    ISSUE VARCHAR(1000),
    ISSUE_CATEGORY VARCHAR(100),
    REPAIR_OR_RETURN VARCHAR(20),
    UNIT_PRICE DECIMAL(10,2),
    REPAIR_COST DECIMAL(10,2),
    
    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ROW_NUMBER_IN_FILE INTEGER,
    
    FOREIGN KEY (SUBMISSION_ID) REFERENCES SCAL_RMA_DB.LANDING.RMA_SUBMISSIONS_RAW(SUBMISSION_ID)
);

-- ============================================================================
-- 4. PRODUCTION ZONE - Analytics-Ready Tables
-- ============================================================================

-- 4.1 Submissions Table
CREATE OR REPLACE TABLE SCAL_RMA_DB.PRODUCTION.RMA_SUBMISSIONS (
    SUBMISSION_ID VARCHAR(50) PRIMARY KEY,
    
    -- Customer Info
    COMPANY_NAME VARCHAR(255) NOT NULL,
    COMPANY_EMAIL VARCHAR(255) NOT NULL,
    ORDER_NUMBER VARCHAR(100),
    CUSTOMER_TYPE VARCHAR(20),
    
    -- Submission Details
    SUBMISSION_DATE DATE NOT NULL,
    INVOICE_NUMBER VARCHAR(100),
    
    -- Counts
    RETURN_QUANTITY INTEGER DEFAULT 0,
    REPAIR_QUANTITY INTEGER DEFAULT 0,
    TOTAL_DEVICES INTEGER,
    
    -- Values
    TOTAL_RETURN_VALUE DECIMAL(10,2) DEFAULT 0,
    TOTAL_REPAIR_VALUE DECIMAL(10,2) DEFAULT 0,
    TOTAL_VALUE DECIMAL(10,2),
    
    -- Status Workflow
    RMA_STATUS VARCHAR(20) DEFAULT 'SUBMITTED',
    APPROVAL_DATE DATE,
    RECEIVED_DATE DATE,
    CREDIT_DATE DATE,
    
    -- Assignment
    ASSIGNED_TO VARCHAR(100),
    NOTES VARCHAR(5000),
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100) DEFAULT 'SYSTEM',
    UPDATED_BY VARCHAR(100)
);

-- 4.2 Devices Table
CREATE OR REPLACE TABLE SCAL_RMA_DB.PRODUCTION.RMA_DEVICES (
    DEVICE_ID VARCHAR(100) PRIMARY KEY,
    SUBMISSION_ID VARCHAR(50),
    
    -- Device Details
    IMEI VARCHAR(15) NOT NULL,
    MODEL VARCHAR(100),
    STORAGE VARCHAR(20),
    STATUS VARCHAR(50),
    
    -- Issue Info
    ISSUE_DESCRIPTION VARCHAR(1000),
    ISSUE_CATEGORY VARCHAR(100),
    
    -- Financial
    ACTION_TYPE VARCHAR(20),
    UNIT_PRICE DECIMAL(10,2),
    REPAIR_COST DECIMAL(10,2),
    
    -- Status Tracking
    DEVICE_STATUS VARCHAR(20) DEFAULT 'PENDING',
    INSPECTION_DATE DATE,
    INSPECTOR_NAME VARCHAR(100),
    INSPECTION_NOTES VARCHAR(2000),
    
    -- Resolution
    FINAL_ACTION VARCHAR(20),
    RESOLUTION_DATE DATE,
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    FOREIGN KEY (SUBMISSION_ID) REFERENCES SCAL_RMA_DB.PRODUCTION.RMA_SUBMISSIONS(SUBMISSION_ID)
);

-- 4.3 Files Table
CREATE OR REPLACE TABLE SCAL_RMA_DB.PRODUCTION.RMA_FILES (
    FILE_ID VARCHAR(100) PRIMARY KEY,
    SUBMISSION_ID VARCHAR(50),
    
    -- File Metadata
    ORIGINAL_FILENAME VARCHAR(500),
    STORED_FILENAME VARCHAR(500),
    FILE_TYPE VARCHAR(50),
    FILE_SIZE_BYTES INTEGER,
    MIME_TYPE VARCHAR(100),
    
    -- Storage
    LOCAL_PATH VARCHAR(1000),
    CLOUD_STORAGE_URL VARCHAR(1000),
    
    -- Processing
    PROCESSING_STATUS VARCHAR(20) DEFAULT 'PENDING',
    EXTRACTED_DATA VARIANT,
    PROCESSING_ERROR VARCHAR(2000),
    
    -- Audit
    UPLOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PROCESSED_AT TIMESTAMP_NTZ,
    
    FOREIGN KEY (SUBMISSION_ID) REFERENCES SCAL_RMA_DB.PRODUCTION.RMA_SUBMISSIONS(SUBMISSION_ID)
);

-- 4.4 Audit Log
CREATE OR REPLACE TABLE SCAL_RMA_DB.PRODUCTION.RMA_AUDIT_LOG (
    AUDIT_ID VARCHAR(100) PRIMARY KEY,
    
    ACTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ACTION_TYPE VARCHAR(50),
    ENTITY_TYPE VARCHAR(50),
    ENTITY_ID VARCHAR(100),
    
    -- User Info
    USER_ID VARCHAR(100),
    USER_EMAIL VARCHAR(255),
    USER_ROLE VARCHAR(50),
    
    -- Changes
    OLD_VALUES VARIANT,
    NEW_VALUES VARIANT,
    CHANGED_FIELDS ARRAY,
    
    -- Context
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(500),
    SESSION_ID VARCHAR(100)
);

-- ============================================================================
-- 5. SYSTEM TABLES - Error Handling & Monitoring
-- ============================================================================

-- 5.1 Processing Queue (Retry Logic)
CREATE OR REPLACE TABLE SCAL_RMA_DB.SYSTEM.PROCESSING_QUEUE (
    QUEUE_ID VARCHAR(100) PRIMARY KEY,
    SUBMISSION_ID VARCHAR(50),
    RETRY_COUNT INTEGER DEFAULT 0,
    MAX_RETRIES INTEGER DEFAULT 3,
    NEXT_RETRY_AT TIMESTAMP_NTZ,
    ERROR_MESSAGE VARCHAR(5000),
    STATUS VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5.2 Failed Submissions (Dead Letter Queue)
CREATE OR REPLACE TABLE SCAL_RMA_DB.SYSTEM.FAILED_SUBMISSIONS (
    FAILURE_ID VARCHAR(100) PRIMARY KEY,
    SUBMISSION_ID VARCHAR(50),
    FAILURE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ERROR_TYPE VARCHAR(100),
    ERROR_MESSAGE VARCHAR(5000),
    RAW_DATA VARIANT,
    REQUIRES_MANUAL_REVIEW BOOLEAN DEFAULT TRUE
);

-- 5.3 Data Quality Rules
CREATE OR REPLACE TABLE SCAL_RMA_DB.SYSTEM.DATA_QUALITY_RULES (
    RULE_ID VARCHAR(100) PRIMARY KEY,
    RULE_NAME VARCHAR(200),
    RULE_TYPE VARCHAR(50),
    TABLE_NAME VARCHAR(100),
    COLUMN_NAME VARCHAR(100),
    VALIDATION_EXPRESSION VARCHAR(2000),
    SEVERITY VARCHAR(20),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- Insert default validation rules
INSERT INTO SCAL_RMA_DB.SYSTEM.DATA_QUALITY_RULES VALUES
    ('R001', 'IMEI Must Be 15 Digits', 'FORMAT', 'RMA_DEVICES', 'IMEI', 'LENGTH(IMEI) = 15', 'ERROR', TRUE),
    ('R002', 'Email Must Be Valid', 'FORMAT', 'RMA_SUBMISSIONS', 'COMPANY_EMAIL', 'RLIKE(COMPANY_EMAIL, ''.*@.*\\..*'')', 'ERROR', TRUE),
    ('R003', 'Unit Price Must Be Positive', 'RANGE', 'RMA_DEVICES', 'UNIT_PRICE', 'UNIT_PRICE > 0', 'WARNING', TRUE),
    ('R004', 'Action Type Must Be Valid', 'ENUM', 'RMA_DEVICES', 'ACTION_TYPE', 'ACTION_TYPE IN (''RETURN'', ''REPAIR'')', 'ERROR', TRUE);

-- 5.4 Pipeline Health Monitoring
CREATE OR REPLACE TABLE SCAL_RMA_DB.SYSTEM.PIPELINE_HEALTH (
    METRIC_ID VARCHAR(100) PRIMARY KEY,
    METRIC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METRIC_NAME VARCHAR(100),
    METRIC_VALUE VARIANT,
    THRESHOLD_VALUE VARIANT,
    IS_HEALTHY BOOLEAN,
    ALERT_SENT BOOLEAN DEFAULT FALSE
);

-- ============================================================================
-- 6. PERFORMANCE OPTIMIZATION
-- ============================================================================

-- Cluster keys for faster queries
ALTER TABLE SCAL_RMA_DB.PRODUCTION.RMA_SUBMISSIONS
CLUSTER BY (SUBMISSION_DATE, RMA_STATUS);

ALTER TABLE SCAL_RMA_DB.PRODUCTION.RMA_DEVICES
CLUSTER BY (SUBMISSION_ID, ACTION_TYPE);

ALTER TABLE SCAL_RMA_DB.PRODUCTION.RMA_AUDIT_LOG
CLUSTER BY (ACTION_TIMESTAMP);

-- Materialized view for daily analytics
CREATE OR REPLACE MATERIALIZED VIEW SCAL_RMA_DB.PRODUCTION.RMA_DAILY_SUMMARY AS
SELECT
    SUBMISSION_DATE,
    CUSTOMER_TYPE,
    COUNT(*) AS TOTAL_SUBMISSIONS,
    SUM(RETURN_QUANTITY) AS TOTAL_RETURNS,
    SUM(REPAIR_QUANTITY) AS TOTAL_REPAIRS,
    SUM(TOTAL_VALUE) AS TOTAL_VALUE,
    AVG(TOTAL_VALUE) AS AVG_VALUE_PER_SUBMISSION
FROM SCAL_RMA_DB.PRODUCTION.RMA_SUBMISSIONS
GROUP BY SUBMISSION_DATE, CUSTOMER_TYPE;

-- ============================================================================
-- 7. WAREHOUSES (Compute Resources)
-- ============================================================================

CREATE OR REPLACE WAREHOUSE RMA_INGESTION_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 5
    SCALING_POLICY = 'STANDARD';

CREATE OR REPLACE WAREHOUSE RMA_PROCESSING_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 10
    SCALING_POLICY = 'STANDARD';

-- ============================================================================
-- 8. DATA RETENTION & ARCHIVAL
-- ============================================================================

-- Enable time travel for recovery
ALTER TABLE SCAL_RMA_DB.PRODUCTION.RMA_SUBMISSIONS
SET DATA_RETENTION_TIME_IN_DAYS = 90;

ALTER TABLE SCAL_RMA_DB.PRODUCTION.RMA_DEVICES
SET DATA_RETENTION_TIME_IN_DAYS = 90;

-- Archive old submissions (automated task)
CREATE OR REPLACE TASK ARCHIVE_OLD_SUBMISSIONS
    WAREHOUSE = 'RMA_PROCESSING_WH'
    SCHEDULE = 'USING CRON 0 2 * * SUN America/Los_Angeles'
AS
    INSERT INTO SCAL_RMA_DB.ARCHIVE.RMA_SUBMISSIONS
    SELECT * FROM SCAL_RMA_DB.PRODUCTION.RMA_SUBMISSIONS
    WHERE SUBMISSION_DATE < DATEADD('day', -365, CURRENT_DATE());

-- ============================================================================
-- SCHEMA COMPLETE
-- ============================================================================
